#############################
# CartoDB Production Instance
#############################
production:
  host: 'https://api.cartodb.com'
  api_key: '00582693b247d2ce465fc8cf3248c3d88837b60e'
  table_name: 'piwi'

#  auth_key: 'NJjm30LDCThhHteEuL8Zf1I2DhJ6qJHvIgpwAH91'
#  oauth_secret: 'zw3wb51WSONT4yUAY8KFcPbboISPavY7l6BwMDaO'
#  table_name: 'zonas_reparto'
#  cache_timeout: 60
#  debug: true
#  ssl_peer_verification: true

#############################
# CartoDB Local Instance
#############################
development:
  host: 'https://api.cartodb.com'
  oauth_key: '04a1lgD53SyMD6AH7Y8utBqX6pucvADrVyhGCAAD'
  oauth_secret: '55Pw5g637raU5Q47BguBKeury6EIKUQg7eCQRCGU'
  table_name: 'mapbrd'
  google_api_key: 'ABQIAAAA0CKawhnQpsJmm-UNAx1vohRWImdktEN2SqC7V1Ko4HIEUqCxXhQOtGCYfIGdkSjeB8P0YC0k-ZYPkg'

